---
# tasks file for powerstore_volume_info
  - name: Get volume details using ID
    dellemc.powerstore.dellemc_powerstore_volume:
     array_ip: "{{array_ip}}"
     verifycert: False
     user: "{{user}}"
     password: "{{password}}"
     vol_name: "demo_volume_arakkal"
     state: "present"
